<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Version>1.0.95</Version>
    <AssemblyName>EmoteLink</AssemblyName>
    <RootNamespace>EmoteLink</RootNamespace>
    <Description>A small Penumbra animation launcher with synchronized group play.</Description>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RestoreEnablePackagePruning>false</RestoreEnablePackagePruning>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.10" />
    <PackageReference Include="NoireLib" Version="2.0.1" GeneratePathProperty="true">
      <ExcludeAssets>analyzers</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="EmoteLink.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <EmbeddedResource Include="Assets\HowTo\*.png" />
  </ItemGroup>
  <Target Name="RemoveNoireLibSourceGenerator" BeforeTargets="CoreCompile">
    <ItemGroup>
      <Analyzer Remove="$(PkgNoireLib)\analyzers\dotnet\cs\NoireLib.SourceGenerators.dll" />
    </ItemGroup>
  </Target>
</Project>
